workflows:
  flutter-ios-sim:
    name: Flutter iOS (Simulator)
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter pub get
      - flutter build ios --simulator --debug
    artifacts:
      - build/ios/iphonesimulator/Runner.app
